name: Run unit tests
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test_config:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: Test config package
        run: |
          go test -v ./...

